### ISSUE TITLE
Link to white paper from the README

### ISSUE THREAD

**Issue by tjayrush** [counterdao/dss#2]
In your README, you say, "assuming familiarity with the basic counting mechanics as described in the whitepaper..." and then oddly do not link the white paper. How can someone who is not familiar with it get familiar with it if it's not easy to find.

You should like to it.

**Comment by horsefacts** [comment]
Thank you for this suggestion! I have added a link to the [original DSS whitepaper](https://archive.org/details/arithmeticespri00peangoog/mode/2up) in the README.

Note that it was published in Latin in 1889, and can be a somewhat difficult read. You may find [this summary](https://en.wikipedia.org/wiki/Peano_axioms) helpful as a companion resource.
